MEMORY_PATH = memory
OBJS += $(MEMORY_PATH)/segments_operations.o $(MEMORY_PATH)/segment.o $(MEMORY_PATH)/paging.o \
		$(MEMORY_PATH)/buddy_system.o $(MEMORY_PATH)/page_operations.o

include common.mk